export interface MonthlyClimateProfile {
  monthIndex: number; // 0 (Jan) to 11 (Dec)
  monthName: string;
  monthShort: string;
  avgAmbientTempC: number;
  relativeHumidityPct: number;
  seasonalMultiplier: number; // e.g. 0.75x to 1.20x
  seasonCategory: 'Winter / Cool Dry' | 'Spring / Warming' | 'Summer / Heatwave' | 'Monsoon / High Moisture' | 'Autumn / Post-Rain';
  respirationStressLevel: 'MINIMAL' | 'LOW' | 'MODERATE' | 'HIGH' | 'CRITICAL';
  agronomicDescription: string;
  fieldManagementTip: string;
}

export interface SupplyRegion {
  id: string;
  name: string;
  shortName: string;
  climateZone: string;
  elevation: string;
  primaryCrops: string;
  months: MonthlyClimateProfile[];
}

export const SUPPLY_REGIONS: SupplyRegion[] = [
  {
    id: 'WESTERN_DECCAN',
    name: 'Western Horticultural Hub (Nashik / Pune)',
    shortName: 'Nashik / Western Belt',
    climateZone: 'Semi-Arid Subtropical (Deccan Plateau)',
    elevation: '560m ASL',
    primaryCrops: 'Tomato, Grape, Pomegranate, Onion',
    months: [
      {
        monthIndex: 0,
        monthName: 'January',
        monthShort: 'Jan',
        avgAmbientTempC: 21,
        relativeHumidityPct: 48,
        seasonalMultiplier: 1.18,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Crisp dry nights, minimal spore load, low cellular respiration.',
        fieldManagementTip: 'Harvest late morning after dew dries. Maximum natural firmness retention.',
      },
      {
        monthIndex: 1,
        monthName: 'February',
        monthShort: 'Feb',
        avgAmbientTempC: 23,
        relativeHumidityPct: 44,
        seasonalMultiplier: 1.14,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Mild diurnal range, optimal harvest transit conditions.',
        fieldManagementTip: 'Ideal shipping window for long-haul interstate distribution (>250 km).',
      },
      {
        monthIndex: 2,
        monthName: 'March',
        monthShort: 'Mar',
        avgAmbientTempC: 28,
        relativeHumidityPct: 38,
        seasonalMultiplier: 1.04,
        seasonCategory: 'Spring / Warming',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Pre-summer solar radiation rises; baseline respiration rates.',
        fieldManagementTip: 'Pre-cool crates before dispatch to preserve pulp turgor.',
      },
      {
        monthIndex: 3,
        monthName: 'April',
        monthShort: 'Apr',
        avgAmbientTempC: 33,
        relativeHumidityPct: 36,
        seasonalMultiplier: 0.88,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'HIGH',
        agronomicDescription: 'Intense midday heat creates elevated pulp field heat at harvest.',
        fieldManagementTip: 'Restrict field picking strictly to dawn (5:30 AM - 8:30 AM) to avoid field heat surge.',
      },
      {
        monthIndex: 4,
        monthName: 'May',
        monthShort: 'May',
        avgAmbientTempC: 36,
        relativeHumidityPct: 45,
        seasonalMultiplier: 0.76,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'CRITICAL',
        agronomicDescription: 'Extreme thermal shock risk during transit; rapid enzymatic softening.',
        fieldManagementTip: 'Enforce chilled reefer transit or reduce transit radius to <8 hours.',
      },
      {
        monthIndex: 5,
        monthName: 'June',
        monthShort: 'Jun',
        avgAmbientTempC: 30,
        relativeHumidityPct: 76,
        seasonalMultiplier: 0.82,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'HIGH',
        agronomicDescription: 'Monsoon onset brings high atmospheric humidity and fungal spore load.',
        fieldManagementTip: 'Ensure crate ventilation holes are unobstructed to prevent moisture condensation.',
      },
      {
        monthIndex: 6,
        monthName: 'July',
        monthShort: 'Jul',
        avgAmbientTempC: 27,
        relativeHumidityPct: 86,
        seasonalMultiplier: 0.85,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Heavy rains increase water content in fruit; softer cellular walls.',
        fieldManagementTip: 'Divert higher maturity batches to immediate fast-track dock dispatch.',
      },
      {
        monthIndex: 7,
        monthName: 'August',
        monthShort: 'Aug',
        avgAmbientTempC: 26,
        relativeHumidityPct: 88,
        seasonalMultiplier: 0.86,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'High relative humidity dampens natural transpiration, accelerating latent skin rot.',
        fieldManagementTip: 'Implement post-harvest sanitization wash and drying fan tunnel.',
      },
      {
        monthIndex: 8,
        monthName: 'September',
        monthShort: 'Sep',
        avgAmbientTempC: 27,
        relativeHumidityPct: 80,
        seasonalMultiplier: 0.90,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Late-monsoon humid transition; moderate respiration with sporadic heat spikes.',
        fieldManagementTip: 'Monitor dock receiving temperatures closely; prioritize FIFO dispatch within 48h.',
      },
      {
        monthIndex: 9,
        monthName: 'October',
        monthShort: 'Oct',
        avgAmbientTempC: 28,
        relativeHumidityPct: 62,
        seasonalMultiplier: 0.98,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Post-monsoon clearing, humidity normalizes, produce firmness stabilizes.',
        fieldManagementTip: 'Standard distribution protocols viable across both ambient and reefer.',
      },
      {
        monthIndex: 10,
        monthName: 'November',
        monthShort: 'Nov',
        avgAmbientTempC: 24,
        relativeHumidityPct: 52,
        seasonalMultiplier: 1.10,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Pleasant winter transition; low nighttime degradation rate.',
        fieldManagementTip: 'Extended shelf-life allows standard ambient transit up to 18 hours.',
      },
      {
        monthIndex: 11,
        monthName: 'December',
        monthShort: 'Dec',
        avgAmbientTempC: 20,
        relativeHumidityPct: 50,
        seasonalMultiplier: 1.20,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Cold nights preserve fruit sugars and natural skin cuticle integrity.',
        fieldManagementTip: 'Peak seasonal longevity; highest marketable days retention of the year.',
      },
    ],
  },
  {
    id: 'SOUTHERN_PLATEAU',
    name: 'Southern Plateau (Bangalore / Kolar Belt)',
    shortName: 'Bangalore / Kolar',
    climateZone: 'Tropical Savanna / Moderate High Plateau',
    elevation: '920m ASL',
    primaryCrops: 'Greenhouse Tomato, Bell Pepper, Hydroponic Greens',
    months: [
      {
        monthIndex: 0,
        monthName: 'January',
        monthShort: 'Jan',
        avgAmbientTempC: 22,
        relativeHumidityPct: 55,
        seasonalMultiplier: 1.12,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Pleasant plateau conditions; stable post-harvest respiration.',
        fieldManagementTip: 'Optimal quality for direct dark-store distribution.',
      },
      {
        monthIndex: 1,
        monthName: 'February',
        monthShort: 'Feb',
        avgAmbientTempC: 25,
        relativeHumidityPct: 48,
        seasonalMultiplier: 1.08,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Dry air with moderate warmth; low fungal pressure.',
        fieldManagementTip: 'Minimal chilling requirement for short-haul (<100 km) routes.',
      },
      {
        monthIndex: 2,
        monthName: 'March',
        monthShort: 'Mar',
        avgAmbientTempC: 28,
        relativeHumidityPct: 45,
        seasonalMultiplier: 1.00,
        seasonCategory: 'Spring / Warming',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Standard baseline climate; predictable ripening curves.',
        fieldManagementTip: 'Use standard baseline kinetic parameters without adjustments.',
      },
      {
        monthIndex: 3,
        monthName: 'April',
        monthShort: 'Apr',
        avgAmbientTempC: 31,
        relativeHumidityPct: 52,
        seasonalMultiplier: 0.90,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Warmest month on plateau; daytime heat elevates respiration.',
        fieldManagementTip: 'Nighttime dispatch recommended for uninsulated lorries.',
      },
      {
        monthIndex: 4,
        monthName: 'May',
        monthShort: 'May',
        avgAmbientTempC: 30,
        relativeHumidityPct: 65,
        seasonalMultiplier: 0.88,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Pre-monsoon thunderstorms; variable moisture levels.',
        fieldManagementTip: 'Inspect crates for dampness before loading into dark store trucks.',
      },
      {
        monthIndex: 5,
        monthName: 'June',
        monthShort: 'Jun',
        avgAmbientTempC: 26,
        relativeHumidityPct: 75,
        seasonalMultiplier: 0.92,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Cooler breeze with frequent rain; elevated skin hydration.',
        fieldManagementTip: 'Monitor blossom-end defect vulnerability on softer skins.',
      },
      {
        monthIndex: 6,
        monthName: 'July',
        monthShort: 'Jul',
        avgAmbientTempC: 25,
        relativeHumidityPct: 78,
        seasonalMultiplier: 0.94,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Continuous mild monsoon; pleasant ambient temps around 25°C.',
        fieldManagementTip: 'Gentle handling required to prevent compression bruising.',
      },
      {
        monthIndex: 7,
        monthName: 'August',
        monthShort: 'Aug',
        avgAmbientTempC: 25,
        relativeHumidityPct: 79,
        seasonalMultiplier: 0.94,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Consistent cloud cover limits solar thermal buildup.',
        fieldManagementTip: 'Stable harvesting window across greenhouse and polyhouse crops.',
      },
      {
        monthIndex: 8,
        monthName: 'September',
        monthShort: 'Sep',
        avgAmbientTempC: 26,
        relativeHumidityPct: 76,
        seasonalMultiplier: 0.95,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Mild post-monsoon; balanced moisture and temperature.',
        fieldManagementTip: 'Reliable predictable shelf-life across urban dark store deliveries.',
      },
      {
        monthIndex: 9,
        monthName: 'October',
        monthShort: 'Oct',
        avgAmbientTempC: 25,
        relativeHumidityPct: 74,
        seasonalMultiplier: 0.98,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Northeast monsoon showers with cool evenings.',
        fieldManagementTip: 'Ensure adequate crate ventilation during transit.',
      },
      {
        monthIndex: 10,
        monthName: 'November',
        monthShort: 'Nov',
        avgAmbientTempC: 23,
        relativeHumidityPct: 68,
        seasonalMultiplier: 1.06,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Cooler weather sets in; respiration drops to favorable levels.',
        fieldManagementTip: 'Produce maintains firmness up to 2 extra days naturally.',
      },
      {
        monthIndex: 11,
        monthName: 'December',
        monthShort: 'Dec',
        avgAmbientTempC: 21,
        relativeHumidityPct: 62,
        seasonalMultiplier: 1.15,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Crisp pleasant winter; excellent post-harvest firmness preservation.',
        fieldManagementTip: 'Premium retail grade yields peak during this harvesting cycle.',
      },
    ],
  },
  {
    id: 'NORTHERN_TEMPERATE',
    name: 'Northern High-Altitude (Himachal / Kashmir)',
    shortName: 'Himachal / Kashmir',
    climateZone: 'Sub-Alpine / Temperate Continental',
    elevation: '1,800m - 2,400m ASL',
    primaryCrops: 'Apple, Pear, Plum, Cold-Hardy Cherry Tomato',
    months: [
      {
        monthIndex: 0,
        monthName: 'January',
        monthShort: 'Jan',
        avgAmbientTempC: 4,
        relativeHumidityPct: 65,
        seasonalMultiplier: 1.35,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Natural sub-chill conditions; near-dormant biological respiration.',
        fieldManagementTip: 'Protect against frostbite and chilling injury during transport.',
      },
      {
        monthIndex: 1,
        monthName: 'February',
        monthShort: 'Feb',
        avgAmbientTempC: 6,
        relativeHumidityPct: 62,
        seasonalMultiplier: 1.30,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Very low metabolic rate, maximum natural storage preservation.',
        fieldManagementTip: 'Ensure unheated trucks do not freeze sensitive thin-skinned varieties.',
      },
      {
        monthIndex: 2,
        monthName: 'March',
        monthShort: 'Mar',
        avgAmbientTempC: 11,
        relativeHumidityPct: 58,
        seasonalMultiplier: 1.22,
        seasonCategory: 'Spring / Warming',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Cool crisp spring thawing; ideal packaging conditions.',
        fieldManagementTip: 'Produce remains crisp with minimal cold-chain energy costs.',
      },
      {
        monthIndex: 3,
        monthName: 'April',
        monthShort: 'Apr',
        avgAmbientTempC: 16,
        relativeHumidityPct: 52,
        seasonalMultiplier: 1.15,
        seasonCategory: 'Spring / Warming',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Mild spring climate; moderate respiration acceleration begins.',
        fieldManagementTip: 'Safe ambient transport across mountain passes.',
      },
      {
        monthIndex: 4,
        monthName: 'May',
        monthShort: 'May',
        avgAmbientTempC: 21,
        relativeHumidityPct: 48,
        seasonalMultiplier: 1.05,
        seasonCategory: 'Spring / Warming',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Warm mountain summer; baseline shelf life applies.',
        fieldManagementTip: 'Standard ambient transport to plains requires insulated cover.',
      },
      {
        monthIndex: 5,
        monthName: 'June',
        monthShort: 'Jun',
        avgAmbientTempC: 24,
        relativeHumidityPct: 56,
        seasonalMultiplier: 0.95,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Peak mountain summer temperatures; descending to plains introduces thermal shock.',
        fieldManagementTip: 'Reefer transit mandatory once entering plains distribution highways.',
      },
      {
        monthIndex: 6,
        monthName: 'July',
        monthShort: 'Jul',
        avgAmbientTempC: 23,
        relativeHumidityPct: 78,
        seasonalMultiplier: 0.90,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Monsoon rains in lower foothills; fungal spore proliferation risk.',
        fieldManagementTip: 'Inspect for scab and humidity blemishes on skin surface.',
      },
      {
        monthIndex: 7,
        monthName: 'August',
        monthShort: 'Aug',
        avgAmbientTempC: 22,
        relativeHumidityPct: 82,
        seasonalMultiplier: 0.92,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Humid apple harvest period; high fruit turgor pressure.',
        fieldManagementTip: 'Careful cushioning needed to prevent micro-bruising on soft skin.',
      },
      {
        monthIndex: 8,
        monthName: 'September',
        monthShort: 'Sep',
        avgAmbientTempC: 19,
        relativeHumidityPct: 68,
        seasonalMultiplier: 1.08,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Crisp autumn days; rapid cooling at sunset halts ethylene production.',
        fieldManagementTip: 'Golden harvest window for long-distance transit across all metros.',
      },
      {
        monthIndex: 9,
        monthName: 'October',
        monthShort: 'Oct',
        avgAmbientTempC: 14,
        relativeHumidityPct: 55,
        seasonalMultiplier: 1.20,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Cool autumn conditions; exceptional natural firmness retention.',
        fieldManagementTip: 'Minimal chilling needed; excellent retail shelf performance.',
      },
      {
        monthIndex: 10,
        monthName: 'November',
        monthShort: 'Nov',
        avgAmbientTempC: 9,
        relativeHumidityPct: 58,
        seasonalMultiplier: 1.28,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Early mountain winter; natural cold preservation.',
        fieldManagementTip: 'Provides extended marketing window with minimal decay losses.',
      },
      {
        monthIndex: 11,
        monthName: 'December',
        monthShort: 'Dec',
        avgAmbientTempC: 5,
        relativeHumidityPct: 62,
        seasonalMultiplier: 1.32,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Deep natural chilling; produce respiration nearly arrested.',
        fieldManagementTip: 'Protect against extreme transit sub-zero temperatures.',
      },
    ],
  },
  {
    id: 'INDO_GANGETIC',
    name: 'Indo-Gangetic Plain (Punjab / Haryana / UP)',
    shortName: 'Punjab / Gangetic Belt',
    climateZone: 'Subtropical Continental with Extreme Seasonal Swings',
    elevation: '210m ASL',
    primaryCrops: 'Open-Field Tomato, Potato, Pea, Kinnow',
    months: [
      {
        monthIndex: 0,
        monthName: 'January',
        monthShort: 'Jan',
        avgAmbientTempC: 13,
        relativeHumidityPct: 82,
        seasonalMultiplier: 1.24,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Cold dense winter fog; high moisture but very low respiration.',
        fieldManagementTip: 'Protect against damp condensation mold; dry before boxing.',
      },
      {
        monthIndex: 1,
        monthName: 'February',
        monthShort: 'Feb',
        avgAmbientTempC: 17,
        relativeHumidityPct: 70,
        seasonalMultiplier: 1.18,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Pleasant spring-like sunny days; peak harvest yield.',
        fieldManagementTip: 'Optimal shipping window for Northern quick-commerce dark stores.',
      },
      {
        monthIndex: 2,
        monthName: 'March',
        monthShort: 'Mar',
        avgAmbientTempC: 24,
        relativeHumidityPct: 55,
        seasonalMultiplier: 1.05,
        seasonCategory: 'Spring / Warming',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Rapid temperature rise begins; harvest while color is breaker stage.',
        fieldManagementTip: 'Harvest at breaker/turning stage to accommodate accelerated warming.',
      },
      {
        monthIndex: 3,
        monthName: 'April',
        monthShort: 'Apr',
        avgAmbientTempC: 31,
        relativeHumidityPct: 35,
        seasonalMultiplier: 0.85,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'HIGH',
        agronomicDescription: 'Dry hot winds (Loo); severe surface dehydration and sunburn risk.',
        fieldManagementTip: 'Shade picked crates immediately in covered farm collection sheds.',
      },
      {
        monthIndex: 4,
        monthName: 'May',
        monthShort: 'May',
        avgAmbientTempC: 37,
        relativeHumidityPct: 32,
        seasonalMultiplier: 0.72,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'CRITICAL',
        agronomicDescription: 'Extreme 40°C+ heatwaves cause instantaneous pulp respiration surge.',
        fieldManagementTip: 'Avoid non-refrigerated transit >4 hours; mandatory hydro-cooling.',
      },
      {
        monthIndex: 5,
        monthName: 'June',
        monthShort: 'Jun',
        avgAmbientTempC: 36,
        relativeHumidityPct: 48,
        seasonalMultiplier: 0.74,
        seasonCategory: 'Summer / Heatwave',
        respirationStressLevel: 'CRITICAL',
        agronomicDescription: 'High thermal heat coupled with incoming monsoon humidity.',
        fieldManagementTip: 'Fast-track dock routing required; discount Grade B upon dock arrival.',
      },
      {
        monthIndex: 6,
        monthName: 'July',
        monthShort: 'Jul',
        avgAmbientTempC: 32,
        relativeHumidityPct: 78,
        seasonalMultiplier: 0.80,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'HIGH',
        agronomicDescription: 'Intense monsoon humidity combined with high 30°C+ ambient heat.',
        fieldManagementTip: 'High pathogen vulnerability; enforce zero standing water in crates.',
      },
      {
        monthIndex: 7,
        monthName: 'August',
        monthShort: 'Aug',
        avgAmbientTempC: 31,
        relativeHumidityPct: 82,
        seasonalMultiplier: 0.82,
        seasonCategory: 'Monsoon / High Moisture',
        respirationStressLevel: 'HIGH',
        agronomicDescription: 'Sultry muggy weather; high respiration acceleration factor.',
        fieldManagementTip: 'Prioritize prompt dark store receiving and refrigerated storage.',
      },
      {
        monthIndex: 8,
        monthName: 'September',
        monthShort: 'Sep',
        avgAmbientTempC: 30,
        relativeHumidityPct: 72,
        seasonalMultiplier: 0.90,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'MODERATE',
        agronomicDescription: 'Monsoon retreats; warm daytime with gradually cooling nights.',
        fieldManagementTip: 'Seasonal transition begins to favor longer dispatch transit windows.',
      },
      {
        monthIndex: 9,
        monthName: 'October',
        monthShort: 'Oct',
        avgAmbientTempC: 26,
        relativeHumidityPct: 56,
        seasonalMultiplier: 1.02,
        seasonCategory: 'Autumn / Post-Rain',
        respirationStressLevel: 'LOW',
        agronomicDescription: 'Clear sunny autumn skies; excellent produce firmness.',
        fieldManagementTip: 'Favorable conditions for both local and regional distribution.',
      },
      {
        monthIndex: 10,
        monthName: 'November',
        monthShort: 'Nov',
        avgAmbientTempC: 19,
        relativeHumidityPct: 62,
        seasonalMultiplier: 1.15,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Crisp winter weather sets in; biological decay slows substantially.',
        fieldManagementTip: 'Extended shelf-life enables standard ambient dark store stocking.',
      },
      {
        monthIndex: 11,
        monthName: 'December',
        monthShort: 'Dec',
        avgAmbientTempC: 14,
        relativeHumidityPct: 75,
        seasonalMultiplier: 1.25,
        seasonCategory: 'Winter / Cool Dry',
        respirationStressLevel: 'MINIMAL',
        agronomicDescription: 'Winter peak; produce remains fresh and crisp for extended durations.',
        fieldManagementTip: 'Lowest annual dock rejection rates observed across all varieties.',
      },
    ],
  },
];

/**
 * Intelligent helper to auto-detect supply region from supplier name or cluster ID
 */
export function detectRegionFromSupplier(supplierName?: string): string {
  if (!supplierName) return 'WESTERN_DECCAN';
  const lower = supplierName.toLowerCase();
  if (lower.includes('himalayan') || lower.includes('kashmir') || lower.includes('orchard') || lower.includes('apple')) {
    return 'NORTHERN_TEMPERATE';
  }
  if (lower.includes('greenfield') || lower.includes('organic') || lower.includes('bangalore') || lower.includes('kolar') || lower.includes('deccan')) {
    return 'SOUTHERN_PLATEAU';
  }
  if (lower.includes('punjab') || lower.includes('gangetic') || lower.includes('haryana') || lower.includes('plains')) {
    return 'INDO_GANGETIC';
  }
  return 'WESTERN_DECCAN';
}

/**
 * Get the monthly climate profile for a region and month index (0-11)
 */
export function getMonthlyClimate(regionId: string, monthIndex: number): MonthlyClimateProfile {
  const region = SUPPLY_REGIONS.find((r) => r.id === regionId) || SUPPLY_REGIONS[0];
  const safeIndex = Math.max(0, Math.min(11, monthIndex));
  return region.months[safeIndex];
}
